<?php

return [
    'update-profile-photo' => env('FEATURE_UPDATE_PROFILE_PHOTO', true),
    'update-password' => env('FEATURE_UPDATE_PASSWORD', true),
    'update-2fa' => env('FEATURE_UPDATE_2FA', true),
    'update-email-verification' => env('FEATURE_UPDATE_EMAIL_VERIFICATION', true),
    'update-user-registration' => env('FEATURE_UPDATE_USER_REGISTRATION', true),
    'update-reset-password' => env('FEATURE_UPDATE_RESET_PASSWORD', true),
    'update-account-deactivation' => env('FEATURE_UPDATE_ACCOUNT_DEACTIVATION', true),

    'update-notification-preferences' => env('FEATURE_UPDATE_NOTIFICATION_PREFERENCES', true),
    'update-account-recovery' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY', true),
    'update-account-activity' => env('FEATURE_UPDATE_ACCOUNT_ACTIVITY', true),
    'update-account-logs' => env('FEATURE_UPDATE_ACCOUNT_LOGS', true),
    'update-account-sessions' => env('FEATURE_UPDATE_ACCOUNT_SESSIONS', true),
    'update-account-devices' => env('FEATURE_UPDATE_ACCOUNT_DEVICES', true),
    'update-account-privacy' => env('FEATURE_UPDATE_ACCOUNT_PRIVACY', true),
    'update-account-security' => env('FEATURE_UPDATE_ACCOUNT_SECURITY', true),
    'update-account-notifications' => env('FEATURE_UPDATE_ACCOUNT_NOTIFICATIONS', true),
    'update-account-preferences' => env('FEATURE_UPDATE_ACCOUNT_PREFERENCES', true),
    'update-account-settings' => env('FEATURE_UPDATE_ACCOUNT_SETTINGS', true),
    'update-account-appearance' => env('FEATURE_UPDATE_ACCOUNT_APPEARANCE', true),
    'update-account-accessibility' => env('FEATURE_UPDATE_ACCOUNT_ACCESSIBILITY', true),
    'update-account-language' => env('FEATURE_UPDATE_ACCOUNT_LANGUAGE', true),
    'update-account-region' => env('FEATURE_UPDATE_ACCOUNT_REGION', true),
    'update-account-timezone' => env('FEATURE_UPDATE_ACCOUNT_TIMEZONE', true),
    'update-account-currency' => env('FEATURE_UPDATE_ACCOUNT_CURRENCY', true),
    'update-account-backup' => env('FEATURE_UPDATE_ACCOUNT_BACKUP', true),
    'update-account-recovery-options' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_OPTIONS', true),
    'update-account-recovery-questions' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_QUESTIONS', true),
    'update-account-recovery-email' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_EMAIL', true),
    'update-account-recovery-sms' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_SMS', true),
    'update-account-recovery-app' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_APP', true),
    'update-account-recovery-backup' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_BACKUP', true),
    'update-account-recovery-keys' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_KEYS', true),
    'update-account-recovery-codes' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_CODES', true),
    'update-account-recovery-links' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_LINKS', true),
    'update-account-recovery-qr' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_QR', true),
    'update-account-recovery-otp' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_OTP', true),
    'update-account-recovery-otp-app' => env('FEATURE_UPDATE_ACCOUNT_RECOVERY_OTP_APP', true),
];
